import Foundation

enum QuestionLibrary {
    // Returns all built-in questions for seeding the database
    static func allQuestions() -> [(text: String, mode: String, category: String)] {
        let wyr = QuestionMode.wouldYouRather.rawValue
        let tod = QuestionMode.truthOrDare.rawValue
        let nhie = QuestionMode.neverHaveIEver.rawValue
        let ice = QuestionMode.icebreaker.rawValue

        var questions: [(String, String, String)] = []

        // WOULD YOU RATHER
        questions += [
            ("Would you rather always have to whisper or always have to shout?", wyr, "family"),
            ("Would you rather have a dog that talks or a cat that understands you?", wyr, "family"),
            ("Would you rather live in a treehouse or a houseboat?", wyr, "family"),
            ("Would you rather be able to fly or be able to teleport?", wyr, "family"),
            ("Would you rather eat nothing but pizza for a month or never eat pizza again?", wyr, "family"),
            ("Would you rather always be 20 minutes late or always be 1 hour early?", wyr, "family"),
            ("Would you rather control the weather or speak to animals?", wyr, "family"),
            ("Would you rather have unlimited ice cream or unlimited tacos?", wyr, "family"),
            ("Would you rather visit the past or the future?", wyr, "family"),
            ("Would you rather be invisible for a day or fly for a day?", wyr, "family"),
            ("Would you rather never use your phone again or never watch TV again?", wyr, "friends"),
            ("Would you rather know how you'll die or when you'll die?", wyr, "friends"),
            ("Would you rather always tell the truth or always lie?", wyr, "friends"),
            ("Would you rather travel the world alone or stay home with your best friend?", wyr, "friends"),
            ("Would you rather be the funniest person in every room or the smartest?", wyr, "friends"),
            ("Would you rather lose all your old memories or never make new ones?", wyr, "friends"),
            ("Would you rather live in a city of 10 million or a town of 100?", wyr, "friends"),
            ("Would you rather give up social media for a year or caffeine forever?", wyr, "friends"),
            ("Would you rather be 20 years older right now or 10 years younger?", wyr, "friends"),
            ("Would you rather be famous and lonely or unknown and beloved?", wyr, "friends"),
            ("Would you rather date someone much older or much younger than you?", wyr, "couples"),
            ("Would you rather go on an adventure vacation or a relaxing beach trip?", wyr, "couples"),
            ("Would you rather always agree with your partner or have passionate debates?", wyr, "couples"),
            ("Would you rather know your partner's entire past or none of it?", wyr, "couples"),
            ("Would you rather have date night every week (surprise) or plan them together?", wyr, "couples"),
            ("Would you rather move to your partner's hometown forever or never visit it?", wyr, "couples"),
            ("Would you rather your partner be your best friend's ex or your ex's best friend?", wyr, "couples"),
            ("Would you rather your partner be extremely messy or extremely controlling about neatness?", wyr, "couples"),
            ("Would you rather have a partner who makes you laugh or one who makes you think?", wyr, "couples"),
            ("Would you rather have a passionate relationship with lots of fights or a calm one that's a little boring?", wyr, "couples"),
            ("Would you rather only communicate by singing or by rhyming?", wyr, "party"),
            ("Would you rather lose your sense of smell or your sense of taste?", wyr, "party"),
            ("Would you rather have hands for feet or feet for hands?", wyr, "party"),
            ("Would you rather eat a live insect or something incredibly spicy?", wyr, "party"),
            ("Would you rather be trapped in a movie for a week or a book for a month?", wyr, "party"),
            ("Would you rather never have to sleep or never have to eat?", wyr, "party"),
            ("Would you rather swap lives with your pet or your boss?", wyr, "party"),
            ("Would you rather have a skip button for awkward moments or a rewind for worst days?", wyr, "party"),
            ("Would you rather discover a new species or a new planet?", wyr, "party"),
            ("Would you rather hiccup for a year or have the sneezes for a month?", wyr, "party"),
            ("Would you rather be able to read minds but never turn it off, or be invisible but only when naked?", wyr, "party"),
            ("Would you rather fight one horse-sized duck or 100 duck-sized horses?", wyr, "party"),
            ("Would you rather always wear wet socks or always have sand in your shoes?", wyr, "friends"),
            ("Would you rather be the best player on a losing team or the worst on a winning team?", wyr, "friends"),
            ("Would you rather have a rewind button for the past hour or a pause button for the present?", wyr, "friends"),
            ("Would you rather never be able to sit down or never be able to stand up?", wyr, "family"),
            ("Would you rather always say what you're thinking or never speak again?", wyr, "friends"),
            ("Would you rather have super speed or super strength?", wyr, "family"),
            ("Would you rather live without the internet for a year or without music for a year?", wyr, "friends"),
            ("Would you rather have a personal chef or a personal driver?", wyr, "friends"),
        ]

        // TRUTH OR DARE
        questions += [
            ("What is the most embarrassing thing you've done in public?", tod, "friends"),
            ("What is something you've never told anyone in this room?", tod, "friends"),
            ("Have you ever talked behind someone's back who is in this room?", tod, "friends"),
            ("What is your most irrational fear?", tod, "family"),
            ("What is the biggest lie you've ever told?", tod, "friends"),
            ("What is your most embarrassing text message you've ever sent?", tod, "friends"),
            ("What is something you're secretly really proud of?", tod, "family"),
            ("Have you ever cheated on a test or exam?", tod, "family"),
            ("What is the most childish thing you still do?", tod, "family"),
            ("If you could only save one thing from your burning house, what would it be?", tod, "family"),
            ("What is something you do when you're alone that you'd never do in front of others?", tod, "friends"),
            ("What is the worst gift you've ever received and who gave it to you?", tod, "friends"),
            ("Have you ever broken something and blamed it on someone else?", tod, "family"),
            ("What is your biggest regret in life so far?", tod, "friends"),
            ("If you could change one decision from your past, what would it be?", tod, "friends"),
            ("What is a habit you have that most people would find strange?", tod, "friends"),
            ("What is the pettiest thing you've ever done?", tod, "friends"),
            ("Have you ever lied to get out of a social event?", tod, "friends"),
            ("What reality TV show would you be most likely to win?", tod, "party"),
            ("If you had to rate your dancing ability 1–10, what would you say?", tod, "party"),
            ("Call a random contact and tell them a joke right now.", tod, "friends"),
            ("Do your best impression of someone in this room.", tod, "party"),
            ("Speak in an accent of your choice for the next 3 rounds.", tod, "party"),
            ("Let someone in the group post something on your social media.", tod, "party"),
            ("Do your best runway walk across the room right now.", tod, "party"),
            ("Do 20 jumping jacks right now, out loud.", tod, "family"),
            ("Freestyle rap about someone in this room for 30 seconds.", tod, "party"),
            ("Text the 5th contact in your phone 'I've been thinking about you' and show us the reply.", tod, "friends"),
            ("Let the group give you a new nickname for the rest of the game.", tod, "party"),
            ("Act out your morning routine in 30 seconds without words.", tod, "family"),
            ("Sing the chorus of the last song you listened to.", tod, "party"),
            ("Tell us the last thing you searched on the internet.", tod, "friends"),
            ("Do your best robot impression for 30 seconds.", tod, "family"),
            ("Switch seats with whoever the group chooses.", tod, "party"),
            ("Give a 30-second motivational speech about something ridiculous like socks.", tod, "party"),
            ("Let the person to your left style your hair however they want for 2 minutes.", tod, "party"),
            ("Talk in slow motion for the next 2 rounds.", tod, "family"),
            ("Speak only in questions for the next 2 rounds.", tod, "party"),
            ("Do a dramatic reading of the last text you received.", tod, "friends"),
            ("Try to lick your elbow.", tod, "family"),
        ]

        // NEVER HAVE I EVER
        questions += [
            ("Never have I ever gone skinny dipping.", nhie, "party"),
            ("Never have I ever lied on my resume.", nhie, "friends"),
            ("Never have I ever cheated on a test.", nhie, "family"),
            ("Never have I ever fallen asleep during a movie at the theater.", nhie, "family"),
            ("Never have I ever pretended to be sick to avoid plans.", nhie, "friends"),
            ("Never have I ever stalked an ex on social media.", nhie, "friends"),
            ("Never have I ever sent a text to the wrong person.", nhie, "family"),
            ("Never have I ever cried at a commercial.", nhie, "family"),
            ("Never have I ever had a crush on a teacher or professor.", nhie, "friends"),
            ("Never have I ever been to a casino.", nhie, "friends"),
            ("Never have I ever pulled an all-nighter.", nhie, "family"),
            ("Never have I ever ridden a motorcycle.", nhie, "friends"),
            ("Never have I ever been on a blind date.", nhie, "friends"),
            ("Never have I ever snuck out of my house.", nhie, "family"),
            ("Never have I ever spent more than $500 on one item of clothing.", nhie, "party"),
            ("Never have I ever broken a bone.", nhie, "family"),
            ("Never have I ever met a celebrity in person.", nhie, "friends"),
            ("Never have I ever been to a concert in another country.", nhie, "friends"),
            ("Never have I ever quit a job on the spot.", nhie, "friends"),
            ("Never have I ever eaten something that was meant for a pet.", nhie, "family"),
            ("Never have I ever accidentally called a teacher 'Mom' or 'Dad'.", nhie, "family"),
            ("Never have I ever laughed so hard I cried.", nhie, "family"),
            ("Never have I ever stayed awake for more than 24 hours.", nhie, "friends"),
            ("Never have I ever gone a full week without showering.", nhie, "party"),
            ("Never have I ever had a nickname that I hated.", nhie, "family"),
            ("Never have I ever re-gifted a present.", nhie, "family"),
            ("Never have I ever Googled myself.", nhie, "friends"),
            ("Never have I ever sung karaoke in public.", nhie, "friends"),
            ("Never have I ever eaten sushi.", nhie, "family"),
            ("Never have I ever traveled alone to a foreign country.", nhie, "friends"),
        ]

        // ICEBREAKERS
        questions += [
            ("What is one thing on your bucket list?", ice, "all"),
            ("What was your favorite cartoon growing up?", ice, "family"),
            ("What superpower would you choose and why?", ice, "family"),
            ("What is your guilty pleasure TV show?", ice, "friends"),
            ("If you could have dinner with any historical figure, who would it be?", ice, "friends"),
            ("What is the most adventurous thing you've ever done?", ice, "friends"),
            ("What skill would you love to wake up and have tomorrow?", ice, "all"),
            ("What is a random fact that most people don't know?", ice, "friends"),
            ("What would your autobiography be titled?", ice, "friends"),
            ("What was your dream job as a kid?", ice, "family"),
            ("What is your go-to karaoke song?", ice, "friends"),
            ("What is one place you want to visit before you die?", ice, "all"),
            ("What is something that always makes you laugh?", ice, "family"),
            ("If you could live in any TV show world, which would you choose?", ice, "friends"),
            ("What is the most interesting thing about you that most people don't know?", ice, "all"),
            ("What app do you spend the most time on?", ice, "friends"),
            ("What is your most useless talent?", ice, "friends"),
            ("If you won a million dollars tomorrow, what's the first thing you'd buy?", ice, "all"),
            ("What is the best meal you've ever eaten?", ice, "family"),
            ("What is something you're learning or trying to improve right now?", ice, "all"),
            ("What is a movie you've watched more than 5 times?", ice, "family"),
            ("If animals could talk, which would be the rudest?", ice, "family"),
            ("What is your most controversial food opinion?", ice, "friends"),
            ("What is a word you always mispronounce?", ice, "friends"),
            ("What would you do on a perfect Saturday with no obligations?", ice, "all"),
            ("What is the best piece of advice you've ever received?", ice, "all"),
            ("What is your earliest memory?", ice, "family"),
            ("What is a smell that brings back a strong memory?", ice, "all"),
            ("If you could only eat one cuisine for the rest of your life, what would it be?", ice, "family"),
            ("What is a talent you wish you had?", ice, "all"),
        ]

        return questions
    }
}
