import Foundation

enum CityData {
    static let cities: [CelestialCity] = [
        CelestialCity(id:  0, name: "New York",       country: "US",  latitude:  40.713, longitude:  -74.006, timezone: "America/New_York"),
        CelestialCity(id:  1, name: "Los Angeles",    country: "US",  latitude:  34.052, longitude: -118.244, timezone: "America/Los_Angeles"),
        CelestialCity(id:  2, name: "Chicago",        country: "US",  latitude:  41.878, longitude:  -87.630, timezone: "America/Chicago"),
        CelestialCity(id:  3, name: "Houston",        country: "US",  latitude:  29.760, longitude:  -95.370, timezone: "America/Chicago"),
        CelestialCity(id:  4, name: "Phoenix",        country: "US",  latitude:  33.448, longitude: -112.074, timezone: "America/Phoenix"),
        CelestialCity(id:  5, name: "Philadelphia",   country: "US",  latitude:  39.952, longitude:  -75.165, timezone: "America/New_York"),
        CelestialCity(id:  6, name: "San Antonio",    country: "US",  latitude:  29.425, longitude:  -98.494, timezone: "America/Chicago"),
        CelestialCity(id:  7, name: "San Diego",      country: "US",  latitude:  32.716, longitude: -117.161, timezone: "America/Los_Angeles"),
        CelestialCity(id:  8, name: "Dallas",         country: "US",  latitude:  32.776, longitude:  -96.797, timezone: "America/Chicago"),
        CelestialCity(id:  9, name: "Denver",         country: "US",  latitude:  39.739, longitude: -104.984, timezone: "America/Denver"),
        CelestialCity(id: 10, name: "Seattle",        country: "US",  latitude:  47.606, longitude: -122.332, timezone: "America/Los_Angeles"),
        CelestialCity(id: 11, name: "Miami",          country: "US",  latitude:  25.775, longitude:  -80.209, timezone: "America/New_York"),
        CelestialCity(id: 12, name: "Atlanta",        country: "US",  latitude:  33.749, longitude:  -84.388, timezone: "America/New_York"),
        CelestialCity(id: 13, name: "Boston",         country: "US",  latitude:  42.360, longitude:  -71.059, timezone: "America/New_York"),
        CelestialCity(id: 14, name: "Minneapolis",    country: "US",  latitude:  44.977, longitude:  -93.265, timezone: "America/Chicago"),
        CelestialCity(id: 15, name: "Portland",       country: "US",  latitude:  45.523, longitude: -122.676, timezone: "America/Los_Angeles"),
        CelestialCity(id: 16, name: "Nashville",      country: "US",  latitude:  36.174, longitude:  -86.767, timezone: "America/Chicago"),
        CelestialCity(id: 17, name: "London",         country: "GB",  latitude:  51.508, longitude:   -0.128, timezone: "Europe/London"),
        CelestialCity(id: 18, name: "Paris",          country: "FR",  latitude:  48.857, longitude:    2.347, timezone: "Europe/Paris"),
        CelestialCity(id: 19, name: "Berlin",         country: "DE",  latitude:  52.520, longitude:   13.405, timezone: "Europe/Berlin"),
        CelestialCity(id: 20, name: "Madrid",         country: "ES",  latitude:  40.416, longitude:   -3.703, timezone: "Europe/Madrid"),
        CelestialCity(id: 21, name: "Rome",           country: "IT",  latitude:  41.890, longitude:   12.490, timezone: "Europe/Rome"),
        CelestialCity(id: 22, name: "Amsterdam",      country: "NL",  latitude:  52.367, longitude:    4.904, timezone: "Europe/Amsterdam"),
        CelestialCity(id: 23, name: "Stockholm",      country: "SE",  latitude:  59.334, longitude:   18.065, timezone: "Europe/Stockholm"),
        CelestialCity(id: 24, name: "Oslo",           country: "NO",  latitude:  59.911, longitude:   10.753, timezone: "Europe/Oslo"),
        CelestialCity(id: 25, name: "Athens",         country: "GR",  latitude:  37.983, longitude:   23.727, timezone: "Europe/Athens"),
        CelestialCity(id: 26, name: "Istanbul",       country: "TR",  latitude:  41.015, longitude:   28.979, timezone: "Europe/Istanbul"),
        CelestialCity(id: 27, name: "Moscow",         country: "RU",  latitude:  55.751, longitude:   37.618, timezone: "Europe/Moscow"),
        CelestialCity(id: 28, name: "Dubai",          country: "AE",  latitude:  25.204, longitude:   55.271, timezone: "Asia/Dubai"),
        CelestialCity(id: 29, name: "Mumbai",         country: "IN",  latitude:  19.076, longitude:   72.878, timezone: "Asia/Kolkata"),
        CelestialCity(id: 30, name: "Delhi",          country: "IN",  latitude:  28.704, longitude:   77.102, timezone: "Asia/Kolkata"),
        CelestialCity(id: 31, name: "Tokyo",          country: "JP",  latitude:  35.690, longitude:  139.692, timezone: "Asia/Tokyo"),
        CelestialCity(id: 32, name: "Beijing",        country: "CN",  latitude:  39.906, longitude:  116.391, timezone: "Asia/Shanghai"),
        CelestialCity(id: 33, name: "Shanghai",       country: "CN",  latitude:  31.228, longitude:  121.474, timezone: "Asia/Shanghai"),
        CelestialCity(id: 34, name: "Seoul",          country: "KR",  latitude:  37.566, longitude:  126.978, timezone: "Asia/Seoul"),
        CelestialCity(id: 35, name: "Singapore",      country: "SG",  latitude:   1.352, longitude:  103.820, timezone: "Asia/Singapore"),
        CelestialCity(id: 36, name: "Sydney",         country: "AU",  latitude: -33.869, longitude:  151.209, timezone: "Australia/Sydney"),
        CelestialCity(id: 37, name: "Melbourne",      country: "AU",  latitude: -37.840, longitude:  144.946, timezone: "Australia/Melbourne"),
        CelestialCity(id: 38, name: "São Paulo",      country: "BR",  latitude: -23.543, longitude:  -46.633, timezone: "America/Sao_Paulo"),
        CelestialCity(id: 39, name: "Buenos Aires",   country: "AR",  latitude: -34.616, longitude:  -58.373, timezone: "America/Argentina/Buenos_Aires"),
        CelestialCity(id: 40, name: "Toronto",        country: "CA",  latitude:  43.654, longitude:  -79.383, timezone: "America/Toronto"),
        CelestialCity(id: 41, name: "Vancouver",      country: "CA",  latitude:  49.246, longitude: -123.116, timezone: "America/Vancouver"),
        CelestialCity(id: 42, name: "Mexico City",    country: "MX",  latitude:  19.428, longitude:  -99.128, timezone: "America/Mexico_City"),
        CelestialCity(id: 43, name: "Honolulu",       country: "US",  latitude:  21.307, longitude: -157.858, timezone: "Pacific/Honolulu"),
        CelestialCity(id: 44, name: "Anchorage",      country: "US",  latitude:  61.218, longitude: -149.900, timezone: "America/Anchorage"),
        CelestialCity(id: 45, name: "Cairo",          country: "EG",  latitude:  30.033, longitude:   31.233, timezone: "Africa/Cairo"),
        CelestialCity(id: 46, name: "Nairobi",        country: "KE",  latitude:  -1.292, longitude:   36.822, timezone: "Africa/Nairobi"),
        CelestialCity(id: 47, name: "Lagos",          country: "NG",  latitude:   6.524, longitude:    3.379, timezone: "Africa/Lagos"),
        CelestialCity(id: 48, name: "Cape Town",      country: "ZA",  latitude: -33.926, longitude:   18.424, timezone: "Africa/Johannesburg"),
        CelestialCity(id: 49, name: "Reykjavik",      country: "IS",  latitude:  64.135, longitude:  -21.895, timezone: "Atlantic/Reykjavik"),
    ]
}
