import Foundation
import SwiftData

/// Seeds realistic sample data on first launch so Stats/History are immediately alive.
/// Guarded by an @AppStorage flag so it runs exactly once. All games are generated by
/// the real deterministic engine + CPU, so totals and category scores are internally valid.
enum SeedData {
    private static let seededFlagKey = "didSeedSampleData_v1"

    @MainActor
    static func seedIfNeeded(context: ModelContext) {
        let defaults = UserDefaults.standard
        if defaults.bool(forKey: seededFlagKey) { return }

        // Profiles.
        let profiles = [
            PlayerProfile(name: "You", symbol: "person.crop.circle.fill"),
            PlayerProfile(name: "Maya", symbol: "person.fill"),
            PlayerProfile(name: "Theo", symbol: "person.fill")
        ]
        profiles.forEach { context.insert($0) }

        // Generate ~30 past games across modes by actually playing them out.
        let calendar = Calendar.current
        let now = Date()
        let names = ["You", "Maya", "Theo", "Pip CPU"]

        for i in 0..<30 {
            guard let day = calendar.date(byAdding: .day, value: -(i + 1), to: now) else { continue }
            let mode: GameMode
            switch i % 4 {
            case 0: mode = .solo
            case 1: mode = .passAndPlay
            case 2: mode = .vsCPU
            default: mode = .daily
            }

            let record = simulateGame(mode: mode, day: day, index: i, names: names)
            context.insert(record)
        }

        // A few Daily results in the archive.
        for i in 0..<6 {
            guard let day = calendar.date(byAdding: .day, value: -(i + 1), to: now) else { continue }
            let seed = DailySeed.seed(for: day, calendar: calendar)
            let key = DailySeed.key(for: day, calendar: calendar)
            let result = simulateSolo(seed: seed)
            context.insert(DailyResult(dayKey: key, date: day, score: result.score, yahtzees: result.yahtzees))
        }

        try? context.save()
        defaults.set(true, forKey: seededFlagKey)
    }

    /// Play a full game with CPU strategy driving every player; return a GameRecord
    /// where "You" is the human reference player (always index 0 when present).
    @MainActor
    private static func simulateGame(mode: GameMode, day: Date, index: Int, names: [String]) -> GameRecord {
        let players: [PlayerState]
        switch mode {
        case .solo, .daily:
            players = [PlayerState(name: "You", isCPU: false, cpuDifficulty: nil)]
        case .passAndPlay:
            players = [
                PlayerState(name: "You", isCPU: false, cpuDifficulty: nil),
                PlayerState(name: index % 2 == 0 ? "Maya" : "Theo", isCPU: false, cpuDifficulty: nil)
            ]
        case .vsCPU:
            players = [
                PlayerState(name: "You", isCPU: false, cpuDifficulty: nil),
                PlayerState(name: "Pip CPU", isCPU: true, cpuDifficulty: .sharp)
            ]
        }

        let seed = DailySeed.seed(for: day) &+ UInt64(index) &* 7919
        let engine = GameEngine(mode: mode, players: players, rng: SeededRNG(seed: seed))

        autoPlay(engine: engine)

        let final = engine.players
        let scores = final.map { $0.grandTotal }
        let me = final.first { $0.name == "You" } ?? final.first
        let winnerName = engine.winner?.name ?? (me?.name ?? "You")
        let myScore = me?.grandTotal ?? 0
        let myYahtzees = (me?.scores[.yahtzee] == Scorer.yahtzeeValue ? 1 : 0) + (me?.yahtzeeBonuses ?? 0)
        let didWin = winnerName == "You"

        return GameRecord(
            date: day,
            mode: mode,
            playerNames: final.map { $0.name },
            finalScores: scores,
            myCategoryScores: me?.scores ?? [:],
            winnerName: winnerName,
            myScore: myScore,
            myYahtzees: myYahtzees,
            didWin: didWin
        )
    }

    private static func simulateSolo(seed: UInt64) -> (score: Int, yahtzees: Int) {
        let player = PlayerState(name: "You", isCPU: false, cpuDifficulty: nil)
        let engine = GameEngine(mode: .daily, players: [player], rng: SeededRNG(seed: seed))
        autoPlay(engine: engine)
        let me = engine.players.first
        let yahtzees = (me?.scores[.yahtzee] == Scorer.yahtzeeValue ? 1 : 0) + (me?.yahtzeeBonuses ?? 0)
        return (me?.grandTotal ?? 0, yahtzees)
    }

    /// Drive the engine to completion using CPUStrategy for every player (including the
    /// "human" reference — produces sensible, valid scores for seed data).
    private static func autoPlay(engine: GameEngine) {
        var safety = 0
        while !engine.isFinished && safety < 5_000 {
            safety += 1
            guard let player = engine.currentPlayer else { break }
            let difficulty = player.cpuDifficulty ?? .sharp

            // Up to 3 rolls, choosing holds between them.
            engine.roll()
            while engine.canRoll {
                let holds = CPUStrategy.chooseHolds(
                    dice: engine.dice, player: player,
                    rollsRemaining: engine.rollsRemaining, difficulty: difficulty
                )
                engine.setHolds(holds)
                engine.roll()
            }
            let cat = CPUStrategy.chooseCategory(dice: engine.dice, player: player) { c in
                engine.preview(c)
            }
            engine.score(cat)
        }
    }
}
