import Foundation

/// Builds doctor-ready exports. CSV is RFC-4180 safe (quotes fields, escapes
/// embedded quotes, uses CRLF line endings).
enum ReportExporter {

    // MARK: - CSV

    static func csv(panelResults: [LabResult], sex: BiologicalSex) -> String {
        csv(results: panelResults, sex: sex, title: "Assay panel export")
    }

    /// Full-history CSV across all panels.
    static func csvAll(results: [LabResult], sex: BiologicalSex) -> String {
        csv(results: results, sex: sex, title: "Assay full export")
    }

    private static func csv(results: [LabResult], sex: BiologicalSex, title: String) -> String {
        let header = ["Draw Date", "Marker", "Category", "Value", "Unit", "Canonical Value", "Canonical Unit", "Status", "Standard Low", "Standard High", "Lab", "Note"]
        var rows: [String] = []
        rows.append(header.map(escape).joined(separator: ","))

        let sorted = results.sorted { $0.drawDate < $1.drawDate }
        for r in sorted {
            let marker = r.marker
            let canon = marker.map { UnitConverter.toCanonical(value: r.value, rawUnit: r.unitRaw, marker: $0) }
            let status = marker.map { RangeEngine.assess(marker: $0, rawValue: r.value, rawUnit: r.unitRaw, sex: sex).status.rawValue } ?? ""
            let std = marker?.standard.range(for: sex)
            let fields: [String] = [
                Fmt.shortDateString(r.drawDate),
                marker?.name ?? r.markerId,
                marker?.category.rawValue ?? "",
                Fmt.value(r.value),
                r.unitRaw,
                canon.map { Fmt.value($0) } ?? "",
                marker?.unit ?? "",
                status,
                std?.low.map { Fmt.value($0) } ?? "",
                std?.high.map { Fmt.value($0) } ?? "",
                r.labName,
                r.note
            ]
            rows.append(fields.map(escape).joined(separator: ","))
        }
        return rows.joined(separator: "\r\n")
    }

    /// RFC-4180 field escaping: always quote, double internal quotes.
    private static func escape(_ field: String) -> String {
        let escaped = field.replacingOccurrences(of: "\"", with: "\"\"")
        return "\"\(escaped)\""
    }

    // MARK: - Plain-text summary

    static func textSummary(panelResults: [LabResult], sex: BiologicalSex) -> String {
        var lines: [String] = []
        let dateLabel = panelResults.first.map { Fmt.date($0.drawDate) } ?? "—"
        let lab = panelResults.first?.labName ?? ""

        lines.append("ASSAY — Lab Panel Summary")
        lines.append("Draw date: \(dateLabel)")
        if !lab.isEmpty { lines.append("Lab: \(lab)") }
        if sex != .unspecified { lines.append("Ranges for: \(sex.rawValue)") }
        lines.append("")

        if let s = StatsEngine.summarize(panelResults: panelResults, sex: sex) {
            lines.append("Overview: \(s.optimalCount) optimal · \(s.inRangeCount) in range · \(s.outOfRangeCount) out of range (score \(s.score)/100)")
            lines.append("")
        }

        let sorted = panelResults.sorted { ($0.marker?.category.rawValue ?? "") < ($1.marker?.category.rawValue ?? "") }
        var currentCategory: String? = nil
        for r in sorted {
            guard let marker = r.marker else { continue }
            if currentCategory != marker.category.rawValue {
                currentCategory = marker.category.rawValue
                lines.append("— \(marker.category.rawValue) —")
            }
            let a = RangeEngine.assess(marker: marker, rawValue: r.value, rawUnit: r.unitRaw, sex: sex)
            let std = marker.standard.range(for: sex)
            let refText = rangeText(std, unit: marker.unit)
            lines.append("• \(marker.name): \(Fmt.value(r.value)) \(r.unitRaw)  [\(a.status.rawValue)]  ref \(refText)")
        }

        lines.append("")
        lines.append("Generated by Assay. For personal tracking and education only — not medical advice. Discuss results with your clinician.")
        return lines.joined(separator: "\n")
    }

    private static func rangeText(_ r: ClinicalRange, unit: String) -> String {
        switch (r.low, r.high) {
        case let (lo?, hi?): return "\(Fmt.value(lo))–\(Fmt.value(hi)) \(unit)"
        case let (lo?, nil): return "≥ \(Fmt.value(lo)) \(unit)"
        case let (nil, hi?): return "≤ \(Fmt.value(hi)) \(unit)"
        case (nil, nil): return "—"
        }
    }
}
