import Foundation

struct Element: Identifiable, Equatable {
    let id: Int  // atomicNumber
    let symbol: String
    let name: String
    let atomicMass: Double
    let category: ElementCategory
    let group: Int?     // nil for f-block (lanthanides/actinides)
    let period: Int
    let electronegativity: Double?  // Pauling scale, nil if N/A
    let meltingPointK: Double?      // nil if unknown
    let boilingPointK: Double?
    let discoveredYear: Int?        // nil if ancient
    let electronConfig: String
    let funFact: String
    let uses: String

    var atomicNumber: Int { id }
    var meltingPointC: Double? { meltingPointK.map { $0 - 273.15 } }
    var boilingPointC: Double? { boilingPointK.map { $0 - 273.15 } }
}

extension Element {
    // swiftlint:disable function_body_length
    static let all: [Element] = [

        // ---- Period 1 ----
        Element(id: 1,   symbol: "H",  name: "Hydrogen",     atomicMass: 1.008,   category: .nonmetal,       group: 1,    period: 1, electronegativity: 2.20, meltingPointK: 14.01,   boilingPointK: 20.28,   discoveredYear: 1766, electronConfig: "1s¹",                         funFact: "Most abundant element in the universe, making up about 75% of all normal matter by mass.", uses: "Fuel cells, rocket propellant, oil refining, ammonia production"),
        Element(id: 2,   symbol: "He", name: "Helium",       atomicMass: 4.003,   category: .nobleGas,       group: 18,   period: 1, electronegativity: nil,  meltingPointK: nil,     boilingPointK: 4.22,    discoveredYear: 1868, electronConfig: "1s²",                         funFact: "The only element that cannot be solidified by cooling alone — it requires pressure.", uses: "Balloons, MRI cooling, welding shielding, deep-sea diving"),

        // ---- Period 2 ----
        Element(id: 3,   symbol: "Li", name: "Lithium",      atomicMass: 6.941,   category: .alkaliMetal,    group: 1,    period: 2, electronegativity: 0.98, meltingPointK: 453.65,  boilingPointK: 1615.0,  discoveredYear: 1817, electronConfig: "[He] 2s¹",                    funFact: "Lithium is so light it can float on water — and it reacts violently with it.", uses: "Rechargeable batteries, psychiatric medication, alloys"),
        Element(id: 4,   symbol: "Be", name: "Beryllium",    atomicMass: 9.012,   category: .alkalineEarth,  group: 2,    period: 2, electronegativity: 1.57, meltingPointK: 1560.0,  boilingPointK: 2742.0,  discoveredYear: 1798, electronConfig: "[He] 2s²",                    funFact: "Beryllium is one of the lightest metals with one of the highest melting points.", uses: "Aerospace alloys, X-ray windows, nuclear reactors, gyroscopes"),
        Element(id: 5,   symbol: "B",  name: "Boron",        atomicMass: 10.811,  category: .metalloid,      group: 13,   period: 2, electronegativity: 2.04, meltingPointK: 2349.0,  boilingPointK: 4200.0,  discoveredYear: 1808, electronConfig: "[He] 2s² 2p¹",               funFact: "Boron is harder than steel and is found in borax soap and Pyrex glass.", uses: "Glass, detergents, fiberglass, semiconductors, nuclear control rods"),
        Element(id: 6,   symbol: "C",  name: "Carbon",       atomicMass: 12.011,  category: .nonmetal,       group: 14,   period: 2, electronegativity: 2.55, meltingPointK: 3823.0,  boilingPointK: 4098.0,  discoveredYear: nil,  electronConfig: "[He] 2s² 2p²",               funFact: "Carbon forms more compounds than any other element — over 10 million known organic compounds.", uses: "Steel, plastics, carbon fiber, diamonds, graphite, fuels"),
        Element(id: 7,   symbol: "N",  name: "Nitrogen",     atomicMass: 14.007,  category: .nonmetal,       group: 15,   period: 2, electronegativity: 3.04, meltingPointK: 63.15,   boilingPointK: 77.36,   discoveredYear: 1772, electronConfig: "[He] 2s² 2p³",               funFact: "Nitrogen makes up 78% of Earth's atmosphere and is essential for all living things.", uses: "Fertilizers, explosives, refrigerants, food preservation"),
        Element(id: 8,   symbol: "O",  name: "Oxygen",       atomicMass: 15.999,  category: .nonmetal,       group: 16,   period: 2, electronegativity: 3.44, meltingPointK: 54.36,   boilingPointK: 90.20,   discoveredYear: 1774, electronConfig: "[He] 2s² 2p⁴",               funFact: "Liquid oxygen is pale blue and highly magnetic, attracted to magnets.", uses: "Breathing, steel making, water treatment, rocket fuel oxidizer"),
        Element(id: 9,   symbol: "F",  name: "Fluorine",     atomicMass: 18.998,  category: .halogen,        group: 17,   period: 2, electronegativity: 3.98, meltingPointK: 53.53,   boilingPointK: 85.03,   discoveredYear: 1886, electronConfig: "[He] 2s² 2p⁵",               funFact: "Fluorine is the most electronegative and reactive of all elements.", uses: "Toothpaste, Teflon, refrigerants, uranium enrichment"),
        Element(id: 10,  symbol: "Ne", name: "Neon",         atomicMass: 20.180,  category: .nobleGas,       group: 18,   period: 2, electronegativity: nil,  meltingPointK: 24.56,   boilingPointK: 27.07,   discoveredYear: 1898, electronConfig: "[He] 2s² 2p⁶",               funFact: "Neon signs are not actually filled with neon — red-orange signs are, but other colors use different gases.", uses: "Signs, lasers, cryogenics, television tubes"),

        // ---- Period 3 ----
        Element(id: 11,  symbol: "Na", name: "Sodium",       atomicMass: 22.990,  category: .alkaliMetal,    group: 1,    period: 3, electronegativity: 0.93, meltingPointK: 370.87,  boilingPointK: 1156.0,  discoveredYear: 1807, electronConfig: "[Ne] 3s¹",                    funFact: "Sodium explodes when it contacts water, yet you consume it daily as table salt.", uses: "Table salt, glass making, soap, street lighting, coolant in nuclear reactors"),
        Element(id: 12,  symbol: "Mg", name: "Magnesium",    atomicMass: 24.305,  category: .alkalineEarth,  group: 2,    period: 3, electronegativity: 1.31, meltingPointK: 923.0,   boilingPointK: 1363.0,  discoveredYear: 1755, electronConfig: "[Ne] 3s²",                    funFact: "Magnesium burns with such bright white light that it was historically used in flash photography.", uses: "Alloys, fireworks, flares, antacids, sports equipment"),
        Element(id: 13,  symbol: "Al", name: "Aluminum",     atomicMass: 26.982,  category: .postTransition, group: 13,   period: 3, electronegativity: 1.61, meltingPointK: 933.47,  boilingPointK: 2792.0,  discoveredYear: 1825, electronConfig: "[Ne] 3s² 3p¹",               funFact: "Aluminum was once more valuable than gold — Napoleon III served honored guests with aluminum cutlery.", uses: "Aircraft, cans, foil, electrical wiring, construction"),
        Element(id: 14,  symbol: "Si", name: "Silicon",      atomicMass: 28.086,  category: .metalloid,      group: 14,   period: 3, electronegativity: 1.90, meltingPointK: 1687.0,  boilingPointK: 3538.0,  discoveredYear: 1824, electronConfig: "[Ne] 3s² 3p²",               funFact: "Silicon Valley is named after this element, the backbone of all modern computing.", uses: "Semiconductors, solar cells, glass, concrete, silicone"),
        Element(id: 15,  symbol: "P",  name: "Phosphorus",   atomicMass: 30.974,  category: .nonmetal,       group: 15,   period: 3, electronegativity: 2.19, meltingPointK: 317.30,  boilingPointK: 550.0,   discoveredYear: 1669, electronConfig: "[Ne] 3s² 3p³",               funFact: "White phosphorus glows in the dark due to slow oxidation — it was the first element discovered since antiquity.", uses: "Fertilizers, matches, detergents, food additives, rat poison"),
        Element(id: 16,  symbol: "S",  name: "Sulfur",       atomicMass: 32.065,  category: .nonmetal,       group: 16,   period: 3, electronegativity: 2.58, meltingPointK: 388.36,  boilingPointK: 717.87,  discoveredYear: nil,  electronConfig: "[Ne] 3s² 3p⁴",               funFact: "Sulfur was burned in ancient Greece to fumigate homes, and its foul smell is associated with volcanoes and hell.", uses: "Sulfuric acid, fertilizers, gunpowder, rubber vulcanization"),
        Element(id: 17,  symbol: "Cl", name: "Chlorine",     atomicMass: 35.453,  category: .halogen,        group: 17,   period: 3, electronegativity: 3.16, meltingPointK: 171.65,  boilingPointK: 239.11,  discoveredYear: 1774, electronConfig: "[Ne] 3s² 3p⁵",               funFact: "Chlorine was the first chemical weapon used in World War I, released by Germany in 1915.", uses: "Water purification, PVC plastic, bleach, disinfectants"),
        Element(id: 18,  symbol: "Ar", name: "Argon",        atomicMass: 39.948,  category: .nobleGas,       group: 18,   period: 3, electronegativity: nil,  meltingPointK: 83.80,   boilingPointK: 87.30,   discoveredYear: 1894, electronConfig: "[Ne] 3s² 3p⁶",               funFact: "Argon makes up about 1% of Earth's atmosphere and is used to fill incandescent light bulbs.", uses: "Light bulbs, welding, semiconductor manufacturing, preserving documents"),

        // ---- Period 4 ----
        Element(id: 19,  symbol: "K",  name: "Potassium",    atomicMass: 39.098,  category: .alkaliMetal,    group: 1,    period: 4, electronegativity: 0.82, meltingPointK: 336.53,  boilingPointK: 1032.0,  discoveredYear: 1807, electronConfig: "[Ar] 4s¹",                    funFact: "Potassium-40 in your body makes you slightly radioactive — each human emits about 4,000 radioactive decays per second.", uses: "Fertilizers, explosives, soap making, food preservation"),
        Element(id: 20,  symbol: "Ca", name: "Calcium",      atomicMass: 40.078,  category: .alkalineEarth,  group: 2,    period: 4, electronegativity: 1.00, meltingPointK: 1115.0,  boilingPointK: 1757.0,  discoveredYear: 1808, electronConfig: "[Ar] 4s²",                    funFact: "Calcium is the 5th most abundant element in Earth's crust and makes up your bones and teeth.", uses: "Cement, plaster, steel making, antacids, dietary supplements"),
        Element(id: 21,  symbol: "Sc", name: "Scandium",     atomicMass: 44.956,  category: .transitionMetal, group: 3,   period: 4, electronegativity: 1.36, meltingPointK: 1814.0,  boilingPointK: 3109.0,  discoveredYear: 1879, electronConfig: "[Ar] 3d¹ 4s²",               funFact: "Scandium was predicted by Mendeleev before its discovery — he called it eka-boron.", uses: "Aerospace alloys, sports equipment, metal halide lamps"),
        Element(id: 22,  symbol: "Ti", name: "Titanium",     atomicMass: 47.867,  category: .transitionMetal, group: 4,   period: 4, electronegativity: 1.54, meltingPointK: 1941.0,  boilingPointK: 3560.0,  discoveredYear: 1791, electronConfig: "[Ar] 3d² 4s²",               funFact: "Titanium is as strong as steel but 45% lighter, and is completely corrosion-resistant.", uses: "Aircraft, implants, spacecraft, pigments, jewelry"),
        Element(id: 23,  symbol: "V",  name: "Vanadium",     atomicMass: 50.942,  category: .transitionMetal, group: 5,   period: 4, electronegativity: 1.63, meltingPointK: 2183.0,  boilingPointK: 3680.0,  discoveredYear: 1801, electronConfig: "[Ar] 3d³ 4s²",               funFact: "Vanadium was independently discovered twice — once in Mexico in 1801 and rediscovered in Sweden in 1830.", uses: "Steel alloys, catalysts, batteries, sulfuric acid production"),
        Element(id: 24,  symbol: "Cr", name: "Chromium",     atomicMass: 51.996,  category: .transitionMetal, group: 6,   period: 4, electronegativity: 1.66, meltingPointK: 2180.0,  boilingPointK: 2944.0,  discoveredYear: 1798, electronConfig: "[Ar] 3d⁵ 4s¹",               funFact: "Chromium gives rubies their red color and emeralds their green — the same element, different contexts.", uses: "Stainless steel, chrome plating, pigments, leather tanning"),
        Element(id: 25,  symbol: "Mn", name: "Manganese",    atomicMass: 54.938,  category: .transitionMetal, group: 7,   period: 4, electronegativity: 1.55, meltingPointK: 1519.0,  boilingPointK: 2334.0,  discoveredYear: 1774, electronConfig: "[Ar] 3d⁵ 4s²",               funFact: "Manganese nodules on the ocean floor contain more manganese than all known land reserves.", uses: "Steel production, batteries, aluminum alloys, fertilizers"),
        Element(id: 26,  symbol: "Fe", name: "Iron",         atomicMass: 55.845,  category: .transitionMetal, group: 8,   period: 4, electronegativity: 1.83, meltingPointK: 1811.0,  boilingPointK: 3134.0,  discoveredYear: nil,  electronConfig: "[Ar] 3d⁶ 4s²",               funFact: "Iron is the most abundant element on Earth by mass and is at the core of our planet.", uses: "Steel, cast iron, magnets, hemoglobin in blood, tools"),
        Element(id: 27,  symbol: "Co", name: "Cobalt",       atomicMass: 58.933,  category: .transitionMetal, group: 9,   period: 4, electronegativity: 1.88, meltingPointK: 1768.0,  boilingPointK: 3200.0,  discoveredYear: 1735, electronConfig: "[Ar] 3d⁷ 4s²",               funFact: "The word 'cobalt' comes from the German 'Kobold' meaning goblin, because miners blamed goblins for the toxic fumes.", uses: "Superalloys, magnets, pigments, vitamin B12, cancer treatment"),
        Element(id: 28,  symbol: "Ni", name: "Nickel",       atomicMass: 58.693,  category: .transitionMetal, group: 10,  period: 4, electronegativity: 1.91, meltingPointK: 1728.0,  boilingPointK: 3186.0,  discoveredYear: 1751, electronConfig: "[Ar] 3d⁸ 4s²",               funFact: "The US five-cent coin is called a 'nickel' but contains only 25% nickel — the rest is copper.", uses: "Stainless steel, coins, batteries, electroplating, catalysts"),
        Element(id: 29,  symbol: "Cu", name: "Copper",       atomicMass: 63.546,  category: .transitionMetal, group: 11,  period: 4, electronegativity: 1.90, meltingPointK: 1357.77, boilingPointK: 2835.0,  discoveredYear: nil,  electronConfig: "[Ar] 3d¹⁰ 4s¹",             funFact: "Copper has natural antimicrobial properties and kills bacteria on contact — copper door handles reduce hospital infections.", uses: "Electrical wiring, plumbing, alloys, coins, electronics"),
        Element(id: 30,  symbol: "Zn", name: "Zinc",         atomicMass: 65.38,   category: .transitionMetal, group: 12,  period: 4, electronegativity: 1.65, meltingPointK: 692.68,  boilingPointK: 1180.0,  discoveredYear: 1746, electronConfig: "[Ar] 3d¹⁰ 4s²",             funFact: "Zinc is essential for human immunity — your body uses over 300 enzymes that depend on zinc.", uses: "Galvanizing steel, alloys, sunscreen, dietary supplements, batteries"),
        Element(id: 31,  symbol: "Ga", name: "Gallium",      atomicMass: 69.723,  category: .postTransition, group: 13,   period: 4, electronegativity: 1.81, meltingPointK: 302.91,  boilingPointK: 2477.0,  discoveredYear: 1875, electronConfig: "[Ar] 3d¹⁰ 4s² 4p¹",         funFact: "Gallium melts in your hand at just 29.8°C (85.6°F) — a trick often demonstrated at science fairs.", uses: "LEDs, solar cells, semiconductors, thermometers, medical imaging"),
        Element(id: 32,  symbol: "Ge", name: "Germanium",    atomicMass: 72.640,  category: .metalloid,      group: 14,   period: 4, electronegativity: 2.01, meltingPointK: 1211.40, boilingPointK: 3106.0,  discoveredYear: 1886, electronConfig: "[Ar] 3d¹⁰ 4s² 4p²",         funFact: "Germanium was predicted by Mendeleev as 'eka-silicon' 15 years before its discovery — all his predictions were correct.", uses: "Fiber optics, semiconductors, infrared optics, solar cells"),
        Element(id: 33,  symbol: "As", name: "Arsenic",      atomicMass: 74.922,  category: .metalloid,      group: 15,   period: 4, electronegativity: 2.18, meltingPointK: 1090.0,  boilingPointK: 887.0,   discoveredYear: 1250, electronConfig: "[Ar] 3d¹⁰ 4s² 4p³",         funFact: "Victorian wallpapers containing arsenic-based green dye may have contributed to Napoleon's death — the wallpaper released arsenic gas in damp conditions.", uses: "Semiconductors, wood preservatives, insecticides, alloys"),
        Element(id: 34,  symbol: "Se", name: "Selenium",     atomicMass: 78.971,  category: .nonmetal,       group: 16,   period: 4, electronegativity: 2.55, meltingPointK: 494.0,   boilingPointK: 958.0,   discoveredYear: 1817, electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁴",         funFact: "Selenium is named after the moon (Selene) because it was found alongside tellurium, which is named after the Earth.", uses: "Glass manufacturing, photocopiers, solar cells, dandruff shampoo"),
        Element(id: 35,  symbol: "Br", name: "Bromine",      atomicMass: 79.904,  category: .halogen,        group: 17,   period: 4, electronegativity: 2.96, meltingPointK: 265.90,  boilingPointK: 332.0,   discoveredYear: 1826, electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁵",         funFact: "Bromine is one of only two elements that are liquid at room temperature (the other being mercury).", uses: "Flame retardants, photography, pesticides, sedatives"),
        Element(id: 36,  symbol: "Kr", name: "Krypton",      atomicMass: 83.798,  category: .nobleGas,       group: 18,   period: 4, electronegativity: nil,  meltingPointK: 115.79,  boilingPointK: 119.93,  discoveredYear: 1898, electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁶",         funFact: "The standard metre was once defined by krypton-86 emission lines — 1,650,763.73 wavelengths of its orange-red light.", uses: "Lighting, lasers, photography flash bulbs"),

        // ---- Period 5 ----
        Element(id: 37,  symbol: "Rb", name: "Rubidium",     atomicMass: 85.468,  category: .alkaliMetal,    group: 1,    period: 5, electronegativity: 0.82, meltingPointK: 312.46,  boilingPointK: 961.0,   discoveredYear: 1861, electronConfig: "[Kr] 5s¹",                    funFact: "Rubidium was discovered by the first use of spectroscopy to find elements — its name means 'deepest red' in Latin.", uses: "Atomic clocks, photovoltaics, medical imaging, fireworks"),
        Element(id: 38,  symbol: "Sr", name: "Strontium",    atomicMass: 87.620,  category: .alkalineEarth,  group: 2,    period: 5, electronegativity: 0.95, meltingPointK: 1050.0,  boilingPointK: 1655.0,  discoveredYear: 1790, electronConfig: "[Kr] 5s²",                    funFact: "Strontium salts burn bright crimson red and are responsible for the red color in fireworks and flares.", uses: "Fireworks, flares, CRT televisions, toothpaste, drilling fluids"),
        Element(id: 39,  symbol: "Y",  name: "Yttrium",      atomicMass: 88.906,  category: .transitionMetal, group: 3,   period: 5, electronegativity: 1.22, meltingPointK: 1799.0,  boilingPointK: 3618.0,  discoveredYear: 1794, electronConfig: "[Kr] 4d¹ 5s²",               funFact: "Yttrium is named after Ytterby village in Sweden — four other elements (Tb, Er, Yb) are also named after this same village.", uses: "LED phosphors, camera lenses, superconductors, cancer treatment"),
        Element(id: 40,  symbol: "Zr", name: "Zirconium",    atomicMass: 91.224,  category: .transitionMetal, group: 4,   period: 5, electronegativity: 1.33, meltingPointK: 2128.0,  boilingPointK: 4682.0,  discoveredYear: 1789, electronConfig: "[Kr] 4d² 5s²",               funFact: "Zirconium is so corrosion-resistant that it's used inside nuclear reactors and artificial gems last virtually forever.", uses: "Nuclear fuel rods, gemstones, ceramics, corrosion-resistant alloys"),
        Element(id: 41,  symbol: "Nb", name: "Niobium",      atomicMass: 92.906,  category: .transitionMetal, group: 5,   period: 5, electronegativity: 1.60, meltingPointK: 2750.0,  boilingPointK: 5017.0,  discoveredYear: 1801, electronConfig: "[Kr] 4d⁴ 5s¹",               funFact: "Niobium was originally named Columbium in the USA — the current name wasn't officially adopted until 1950.", uses: "Superalloys, superconducting magnets, jet engines, pipelines"),
        Element(id: 42,  symbol: "Mo", name: "Molybdenum",   atomicMass: 95.960,  category: .transitionMetal, group: 6,   period: 5, electronegativity: 2.16, meltingPointK: 2896.0,  boilingPointK: 4912.0,  discoveredYear: 1781, electronConfig: "[Kr] 4d⁵ 5s¹",               funFact: "Molybdenum has the 6th highest melting point of all elements and is essential for nitrogen fixation in plants.", uses: "Stainless steel, lubricants, pigments, catalysts, fertilizers"),
        Element(id: 43,  symbol: "Tc", name: "Technetium",   atomicMass: 98.000,  category: .transitionMetal, group: 7,   period: 5, electronegativity: 1.90, meltingPointK: 2430.0,  boilingPointK: 4538.0,  discoveredYear: 1937, electronConfig: "[Kr] 4d⁵ 5s²",               funFact: "Technetium was the first element to be artificially produced — it doesn't exist naturally on Earth.", uses: "Medical imaging (bone scans), nuclear medicine diagnostics"),
        Element(id: 44,  symbol: "Ru", name: "Ruthenium",    atomicMass: 101.070, category: .transitionMetal, group: 8,   period: 5, electronegativity: 2.20, meltingPointK: 2607.0,  boilingPointK: 4423.0,  discoveredYear: 1844, electronConfig: "[Kr] 4d⁷ 5s¹",               funFact: "Ruthenium is named after Ruthenia, the Latin name for Russia — it was discovered in the Ural Mountains.", uses: "Electrical contacts, solar cells, catalysis, fountain pen nibs"),
        Element(id: 45,  symbol: "Rh", name: "Rhodium",      atomicMass: 102.906, category: .transitionMetal, group: 9,   period: 5, electronegativity: 2.28, meltingPointK: 2237.0,  boilingPointK: 3968.0,  discoveredYear: 1803, electronConfig: "[Kr] 4d⁸ 5s¹",               funFact: "Rhodium is the rarest and most expensive precious metal — more than 40 times the price of gold.", uses: "Catalytic converters, jewelry plating, electrical contacts"),
        Element(id: 46,  symbol: "Pd", name: "Palladium",    atomicMass: 106.420, category: .transitionMetal, group: 10,  period: 5, electronegativity: 2.20, meltingPointK: 1828.05, boilingPointK: 3236.0,  discoveredYear: 1803, electronConfig: "[Kr] 4d¹⁰",                  funFact: "Palladium can absorb up to 900 times its own volume of hydrogen gas at room temperature.", uses: "Catalytic converters, hydrogen purification, jewelry, electronics"),
        Element(id: 47,  symbol: "Ag", name: "Silver",       atomicMass: 107.868, category: .transitionMetal, group: 11,  period: 5, electronegativity: 1.93, meltingPointK: 1234.93, boilingPointK: 2435.0,  discoveredYear: nil,  electronConfig: "[Kr] 4d¹⁰ 5s¹",             funFact: "Silver has the highest electrical conductivity and thermal conductivity of any element.", uses: "Jewelry, photography, electronics, mirrors, antibacterial products"),
        Element(id: 48,  symbol: "Cd", name: "Cadmium",      atomicMass: 112.414, category: .transitionMetal, group: 12,  period: 5, electronegativity: 1.69, meltingPointK: 594.22,  boilingPointK: 1040.0,  discoveredYear: 1817, electronConfig: "[Kr] 4d¹⁰ 5s²",             funFact: "Cadmium poisoning in Japan caused Itai-itai disease ('it hurts' disease) in the 1950s from contaminated rice paddies.", uses: "Rechargeable batteries, pigments, nuclear reactor control rods, coatings"),
        Element(id: 49,  symbol: "In", name: "Indium",       atomicMass: 114.818, category: .postTransition, group: 13,   period: 5, electronegativity: 1.78, meltingPointK: 429.75,  boilingPointK: 2345.0,  discoveredYear: 1863, electronConfig: "[Kr] 4d¹⁰ 5s² 5p¹",         funFact: "Indium makes a distinctive 'cry' or creaking sound when bent due to twinning of its crystal structure.", uses: "Touchscreens (ITO), LCD displays, solders, bearings"),
        Element(id: 50,  symbol: "Sn", name: "Tin",          atomicMass: 118.710, category: .postTransition, group: 14,   period: 5, electronegativity: 1.96, meltingPointK: 505.08,  boilingPointK: 2875.0,  discoveredYear: nil,  electronConfig: "[Kr] 4d¹⁰ 5s² 5p²",         funFact: "Tin pest — at temperatures below 13.2°C, tin slowly crumbles to a gray powder, which may have contributed to Napoleon's defeat in Russia.", uses: "Tin cans, solder, bronze alloy, glass coating, bearings"),
        Element(id: 51,  symbol: "Sb", name: "Antimony",     atomicMass: 121.760, category: .metalloid,      group: 15,   period: 5, electronegativity: 2.05, meltingPointK: 903.78,  boilingPointK: 1860.0,  discoveredYear: nil,  electronConfig: "[Kr] 4d¹⁰ 5s² 5p³",         funFact: "Ancient Egyptians used antimony sulfide as eye makeup — kohl was made from stibnite (antimony sulfide).", uses: "Flame retardants, lead-acid batteries, semiconductors, alloys"),
        Element(id: 52,  symbol: "Te", name: "Tellurium",    atomicMass: 127.600, category: .metalloid,      group: 16,   period: 5, electronegativity: 2.10, meltingPointK: 722.66,  boilingPointK: 1261.0,  discoveredYear: 1782, electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁴",         funFact: "Workers exposed to small amounts of tellurium develop 'tellurium breath' — a garlic-like odor that persists for weeks.", uses: "Solar cells, thermoelectric devices, rubber manufacturing, DVDs"),
        Element(id: 53,  symbol: "I",  name: "Iodine",       atomicMass: 126.904, category: .halogen,        group: 17,   period: 5, electronegativity: 2.66, meltingPointK: 386.85,  boilingPointK: 457.40,  discoveredYear: 1811, electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁵",         funFact: "Iodine is the heaviest element required for life. Without it in the diet, the thyroid gland enlarges to form a goiter.", uses: "Thyroid medication, antiseptics, photography, water purification"),
        Element(id: 54,  symbol: "Xe", name: "Xenon",        atomicMass: 131.293, category: .nobleGas,       group: 18,   period: 5, electronegativity: nil,  meltingPointK: 161.36,  boilingPointK: 165.03,  discoveredYear: 1898, electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁶",         funFact: "Xenon can form compounds despite being a noble gas — XeF₄ was the first noble gas compound ever synthesized.", uses: "Flash lamps, ion thrusters, anesthesia, nuclear physics research"),

        // ---- Period 6 ----
        Element(id: 55,  symbol: "Cs", name: "Caesium",      atomicMass: 132.905, category: .alkaliMetal,    group: 1,    period: 6, electronegativity: 0.79, meltingPointK: 301.59,  boilingPointK: 944.0,   discoveredYear: 1860, electronConfig: "[Xe] 6s¹",                    funFact: "Caesium defines our measurement of time — atomic clocks based on caesium are accurate to 1 second in 300 million years.", uses: "Atomic clocks, drilling fluids, photoelectric cells, catalysts"),
        Element(id: 56,  symbol: "Ba", name: "Barium",       atomicMass: 137.327, category: .alkalineEarth,  group: 2,    period: 6, electronegativity: 0.89, meltingPointK: 1000.0,  boilingPointK: 2143.0,  discoveredYear: 1808, electronConfig: "[Xe] 6s²",                    funFact: "Barium sulfate is swallowed as a 'barium meal' — it's opaque to X-rays and allows imaging of the digestive tract.", uses: "X-ray imaging, fireworks (green), drilling mud, glass making"),

        // Lanthanides (f-block, Period 6)
        Element(id: 57,  symbol: "La", name: "Lanthanum",    atomicMass: 138.905, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.10, meltingPointK: 1193.0,  boilingPointK: 3737.0,  discoveredYear: 1839, electronConfig: "[Xe] 5d¹ 6s²",               funFact: "Lanthanum gives its name to the entire lanthanide series and is used in night-vision goggles.", uses: "Camera lenses, night-vision, hydrogen sponge batteries, studio lighting"),
        Element(id: 58,  symbol: "Ce", name: "Cerium",       atomicMass: 140.116, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.12, meltingPointK: 1071.0,  boilingPointK: 3697.0,  discoveredYear: 1803, electronConfig: "[Xe] 4f¹ 5d¹ 6s²",           funFact: "Cerium is the most abundant rare-earth element and is used to make the flints in cigarette lighters.", uses: "Catalytic converters, lighter flints, glass polishing, UV filters"),
        Element(id: 59,  symbol: "Pr", name: "Praseodymium", atomicMass: 140.908, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.13, meltingPointK: 1208.0,  boilingPointK: 3793.0,  discoveredYear: 1885, electronConfig: "[Xe] 4f³ 6s²",               funFact: "Praseodymium means 'green twin' in Greek — its name refers to the green color of its salts.", uses: "Magnets, aircraft engines, welding goggles, fiber optic amplifiers"),
        Element(id: 60,  symbol: "Nd", name: "Neodymium",    atomicMass: 144.242, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.14, meltingPointK: 1297.0,  boilingPointK: 3347.0,  discoveredYear: 1885, electronConfig: "[Xe] 4f⁴ 6s²",               funFact: "Neodymium magnets are the strongest permanent magnets ever made — a small coin-sized magnet can lift over 300 times its weight.", uses: "Super-strong magnets, wind turbines, electric cars, headphones"),
        Element(id: 61,  symbol: "Pm", name: "Promethium",   atomicMass: 145.000, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.13, meltingPointK: 1315.0,  boilingPointK: 3273.0,  discoveredYear: 1945, electronConfig: "[Xe] 4f⁵ 6s²",               funFact: "Promethium is one of only two non-radioactive elements discovered after 1913 to not have any stable isotopes.", uses: "Nuclear batteries (space probes), atomic research, specialty lighting"),
        Element(id: 62,  symbol: "Sm", name: "Samarium",     atomicMass: 150.360, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.17, meltingPointK: 1345.0,  boilingPointK: 2067.0,  discoveredYear: 1879, electronConfig: "[Xe] 4f⁶ 6s²",               funFact: "Samarium-cobalt magnets maintain their magnetism up to 700°C — far beyond neodymium magnets.", uses: "Samarium-cobalt magnets, neutron absorbers, cancer treatment"),
        Element(id: 63,  symbol: "Eu", name: "Europium",     atomicMass: 151.964, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.20, meltingPointK: 1099.0,  boilingPointK: 1802.0,  discoveredYear: 1901, electronConfig: "[Xe] 4f⁷ 6s²",               funFact: "Europium phosphors create the red color in color TVs and are used as anti-counterfeiting measures in Euro banknotes.", uses: "Red phosphors in screens, anti-counterfeiting dyes, fluorescent lighting"),
        Element(id: 64,  symbol: "Gd", name: "Gadolinium",   atomicMass: 157.250, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.20, meltingPointK: 1586.0,  boilingPointK: 3546.0,  discoveredYear: 1880, electronConfig: "[Xe] 4f⁷ 5d¹ 6s²",           funFact: "Gadolinium-based contrast agents are injected during MRI scans to highlight tumors and blood vessels.", uses: "MRI contrast agent, nuclear reactor shielding, magneto-optical storage"),
        Element(id: 65,  symbol: "Tb", name: "Terbium",      atomicMass: 158.925, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.10, meltingPointK: 1629.0,  boilingPointK: 3503.0,  discoveredYear: 1843, electronConfig: "[Xe] 4f⁹ 6s²",               funFact: "Terbium changes dimensions when placed in a magnetic field — a property called magnetostriction used in sonar.", uses: "Green phosphors, fuel cell catalysts, smart materials, sonar"),
        Element(id: 66,  symbol: "Dy", name: "Dysprosium",   atomicMass: 162.500, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.22, meltingPointK: 1680.0,  boilingPointK: 2840.0,  discoveredYear: 1886, electronConfig: "[Xe] 4f¹⁰ 6s²",              funFact: "Dysprosium's name means 'hard to get' in Greek — it took chemist Paul Emile Lecoq de Boisbaudran years to isolate it.", uses: "Electric vehicle motors, wind turbines, laser materials, nuclear reactors"),
        Element(id: 67,  symbol: "Ho", name: "Holmium",      atomicMass: 164.930, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.23, meltingPointK: 1734.0,  boilingPointK: 2993.0,  discoveredYear: 1878, electronConfig: "[Xe] 4f¹¹ 6s²",              funFact: "Holmium has the highest magnetic moment of any naturally occurring element.", uses: "Magnets, nuclear reactors, lasers, magnetic flux concentrators"),
        Element(id: 68,  symbol: "Er", name: "Erbium",       atomicMass: 167.259, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.24, meltingPointK: 1802.0,  boilingPointK: 3141.0,  discoveredYear: 1843, electronConfig: "[Xe] 4f¹² 6s²",              funFact: "Erbium is the key element in fiber optic communications — erbium-doped amplifiers boost signals over long distances.", uses: "Fiber optic amplifiers, lasers, pink glass coloring, neutron absorbers"),
        Element(id: 69,  symbol: "Tm", name: "Thulium",      atomicMass: 168.934, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.25, meltingPointK: 1818.0,  boilingPointK: 2223.0,  discoveredYear: 1879, electronConfig: "[Xe] 4f¹³ 6s²",              funFact: "Thulium is one of the rarest lanthanides but can be used to make portable X-ray devices powered by radioactive decay.", uses: "Portable X-ray machines, lasers, doping fiber amplifiers"),
        Element(id: 70,  symbol: "Yb", name: "Ytterbium",    atomicMass: 173.045, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.10, meltingPointK: 1097.0,  boilingPointK: 1469.0,  discoveredYear: 1878, electronConfig: "[Xe] 4f¹⁴ 6s²",              funFact: "Ytterbium atomic clocks are 10 times more precise than cesium clocks and may redefine the second.", uses: "Atomic clocks, ground improvement devices, lasers, stainless steel"),
        Element(id: 71,  symbol: "Lu", name: "Lutetium",     atomicMass: 174.967, category: .lanthanide,     group: nil,  period: 6, electronegativity: 1.27, meltingPointK: 1936.0,  boilingPointK: 3675.0,  discoveredYear: 1907, electronConfig: "[Xe] 4f¹⁴ 5d¹ 6s²",          funFact: "Lutetium is the last and hardest of the lanthanides — it's named after Lutetia, the Roman name for Paris.", uses: "PET scan detectors, cancer radiation therapy, catalyst cracking"),

        // Period 6 continued (d-block)
        Element(id: 72,  symbol: "Hf", name: "Hafnium",      atomicMass: 178.490, category: .transitionMetal, group: 4,   period: 6, electronegativity: 1.30, meltingPointK: 2506.0,  boilingPointK: 4876.0,  discoveredYear: 1923, electronConfig: "[Xe] 4f¹⁴ 5d² 6s²",          funFact: "Hafnium is nearly impossible to separate from zirconium — they are chemically almost identical, yet hafnium absorbs neutrons while zirconium does not.", uses: "Nuclear reactor control rods, microchips, superalloys, lighting"),
        Element(id: 73,  symbol: "Ta", name: "Tantalum",     atomicMass: 180.948, category: .transitionMetal, group: 5,   period: 6, electronegativity: 1.50, meltingPointK: 3290.0,  boilingPointK: 5731.0,  discoveredYear: 1802, electronConfig: "[Xe] 4f¹⁴ 5d³ 6s²",          funFact: "Tantalum is biocompatible and corrosion-proof — surgical implants, pacemakers, and hip replacements use it without rejection.", uses: "Capacitors in smartphones, surgical implants, superalloys, cutting tools"),
        Element(id: 74,  symbol: "W",  name: "Tungsten",     atomicMass: 183.840, category: .transitionMetal, group: 6,   period: 6, electronegativity: 2.36, meltingPointK: 3695.0,  boilingPointK: 5828.0,  discoveredYear: 1783, electronConfig: "[Xe] 4f¹⁴ 5d⁴ 6s²",          funFact: "Tungsten has the highest melting point of any element — light bulb filaments survive temperatures over 2500°C because of this.", uses: "Light bulb filaments, cutting tools, armor-piercing ammunition, X-ray targets"),
        Element(id: 75,  symbol: "Re", name: "Rhenium",      atomicMass: 186.207, category: .transitionMetal, group: 7,   period: 6, electronegativity: 1.90, meltingPointK: 3459.0,  boilingPointK: 5869.0,  discoveredYear: 1925, electronConfig: "[Xe] 4f¹⁴ 5d⁵ 6s²",          funFact: "Rhenium was the last stable element to be discovered — all elements discovered after it are radioactive.", uses: "Jet engine superalloys, catalysts, thermocouples, filaments"),
        Element(id: 76,  symbol: "Os", name: "Osmium",       atomicMass: 190.230, category: .transitionMetal, group: 8,   period: 6, electronegativity: 2.20, meltingPointK: 3306.0,  boilingPointK: 5285.0,  discoveredYear: 1803, electronConfig: "[Xe] 4f¹⁴ 5d⁶ 6s²",          funFact: "Osmium is the densest naturally occurring element — a golf-ball-sized lump weighs over 1.4 kg (3 lbs).", uses: "Electrical contacts, fountain pen tips, bearings, staining tissues"),
        Element(id: 77,  symbol: "Ir", name: "Iridium",      atomicMass: 192.217, category: .transitionMetal, group: 9,   period: 6, electronegativity: 2.20, meltingPointK: 2719.0,  boilingPointK: 4403.0,  discoveredYear: 1803, electronConfig: "[Xe] 4f¹⁴ 5d⁷ 6s²",          funFact: "High iridium levels in the geological layer between the Cretaceous and Paleogene periods is key evidence for the asteroid impact that killed the dinosaurs.", uses: "Spark plugs, crucibles, standards, cancer treatment, pen tips"),
        Element(id: 78,  symbol: "Pt", name: "Platinum",     atomicMass: 195.084, category: .transitionMetal, group: 10,  period: 6, electronegativity: 2.28, meltingPointK: 2041.40, boilingPointK: 4098.0,  discoveredYear: 1735, electronConfig: "[Xe] 4f¹⁴ 5d⁹ 6s¹",          funFact: "The international kilogram standard was a platinum-iridium cylinder kept in France for over 130 years.", uses: "Jewelry, catalytic converters, chemotherapy drugs, electronics"),
        Element(id: 79,  symbol: "Au", name: "Gold",         atomicMass: 196.967, category: .transitionMetal, group: 11,  period: 6, electronegativity: 2.54, meltingPointK: 1337.33, boilingPointK: 3129.0,  discoveredYear: nil,  electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",         funFact: "Gold is so malleable that one ounce can be hammered into a sheet 30 square meters in area — thin enough to see through.", uses: "Jewelry, electronics, dentistry, monetary standard, space technology"),
        Element(id: 80,  symbol: "Hg", name: "Mercury",      atomicMass: 200.592, category: .transitionMetal, group: 12,  period: 6, electronegativity: 2.00, meltingPointK: 234.32,  boilingPointK: 629.88,  discoveredYear: nil,  electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",         funFact: "Mercury is the only metal that is liquid at room temperature — a 1 kg block is a sphere only about 6 cm across.", uses: "Thermometers, fluorescent lights, dental amalgam, electrical switches"),
        Element(id: 81,  symbol: "Tl", name: "Thallium",     atomicMass: 204.383, category: .postTransition, group: 13,   period: 6, electronegativity: 1.62, meltingPointK: 577.0,   boilingPointK: 1746.0,  discoveredYear: 1861, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",    funFact: "Thallium poisoning was once used as rat poison and a murder weapon — it's odorless, tasteless, and causes hair loss before death.", uses: "Electronics, gamma radiation detectors, heart disease diagnosis"),
        Element(id: 82,  symbol: "Pb", name: "Lead",         atomicMass: 207.200, category: .postTransition, group: 14,   period: 6, electronegativity: 2.33, meltingPointK: 600.61,  boilingPointK: 2022.0,  discoveredYear: nil,  electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",    funFact: "The fall of the Roman Empire has been partially attributed to lead poisoning — Romans used lead pipes, pots, and even lead-sweetened wine.", uses: "Batteries, radiation shielding, weights, plumbing, bullets"),
        Element(id: 83,  symbol: "Bi", name: "Bismuth",      atomicMass: 208.980, category: .postTransition, group: 15,   period: 6, electronegativity: 2.02, meltingPointK: 544.55,  boilingPointK: 1837.0,  discoveredYear: 1753, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",    funFact: "Bismuth crystals form stunning rainbow-colored hopper structures due to thin oxide layers that refract light.", uses: "Pepto-Bismol, cosmetics, fire alarms, non-toxic bullets, solders"),
        Element(id: 84,  symbol: "Po", name: "Polonium",     atomicMass: 209.000, category: .postTransition, group: 16,   period: 6, electronegativity: 2.00, meltingPointK: 527.0,   boilingPointK: 1235.0,  discoveredYear: 1898, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",    funFact: "Marie Curie discovered polonium and named it after her homeland Poland — she never knew about its extreme toxicity.", uses: "Anti-static devices, neutron sources, thermoelectric generators"),
        Element(id: 85,  symbol: "At", name: "Astatine",     atomicMass: 210.000, category: .halogen,        group: 17,   period: 6, electronegativity: 2.20, meltingPointK: 575.0,   boilingPointK: 610.0,   discoveredYear: 1940, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",    funFact: "Astatine is the rarest naturally occurring element — the entire Earth contains only about 30 grams at any given time.", uses: "Cancer treatment (targeted alpha therapy), research"),
        Element(id: 86,  symbol: "Rn", name: "Radon",        atomicMass: 222.000, category: .nobleGas,       group: 18,   period: 6, electronegativity: nil,  meltingPointK: 202.0,   boilingPointK: 211.3,   discoveredYear: 1900, electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",    funFact: "Radon seeping into basements from bedrock is the second leading cause of lung cancer after smoking.", uses: "Cancer treatment, geological research, earthquake prediction"),

        // ---- Period 7 ----
        Element(id: 87,  symbol: "Fr", name: "Francium",     atomicMass: 223.000, category: .alkaliMetal,    group: 1,    period: 7, electronegativity: 0.70, meltingPointK: 300.0,   boilingPointK: 950.0,   discoveredYear: 1939, electronConfig: "[Rn] 7s¹",                    funFact: "Francium is so radioactive that at most 20-30 atoms have ever been observed together — there is only 30g in all of Earth's crust.", uses: "Research purposes only — no practical uses"),
        Element(id: 88,  symbol: "Ra", name: "Radium",       atomicMass: 226.000, category: .alkalineEarth,  group: 2,    period: 7, electronegativity: 0.90, meltingPointK: 973.0,   boilingPointK: 2010.0,  discoveredYear: 1898, electronConfig: "[Rn] 7s²",                    funFact: "Radium was once used in glow-in-the-dark watch dials — factory workers called 'Radium Girls' who painted them suffered terrible radiation poisoning.", uses: "Cancer treatment (historical), luminous paint (historical), research"),

        // Actinides (f-block, Period 7)
        Element(id: 89,  symbol: "Ac", name: "Actinium",     atomicMass: 227.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.10, meltingPointK: 1500.0,  boilingPointK: 3471.0,  discoveredYear: 1899, electronConfig: "[Rn] 6d¹ 7s²",               funFact: "Actinium glows blue in the dark due to intense radioactivity ionizing surrounding air — it's 150 times more radioactive than radium.", uses: "Cancer treatment (actinium-225), neutron source, research"),
        Element(id: 90,  symbol: "Th", name: "Thorium",      atomicMass: 232.038, category: .actinide,       group: nil,  period: 7, electronegativity: 1.30, meltingPointK: 2023.0,  boilingPointK: 5061.0,  discoveredYear: 1829, electronConfig: "[Rn] 6d² 7s²",               funFact: "Thorium fuel cycle could power civilization for thousands of years — some estimate it can produce 200 times more energy than uranium.", uses: "Nuclear fuel (experimental), catalysts, light mantles, alloys"),
        Element(id: 91,  symbol: "Pa", name: "Protactinium", atomicMass: 231.036, category: .actinide,       group: nil,  period: 7, electronegativity: 1.50, meltingPointK: 1841.0,  boilingPointK: 4300.0,  discoveredYear: 1913, electronConfig: "[Rn] 5f² 6d¹ 7s²",           funFact: "Protactinium is one of the rarest and most expensive naturally occurring elements — one gram costs over $280,000.", uses: "Research only — no commercial uses due to rarity and radioactivity"),
        Element(id: 92,  symbol: "U",  name: "Uranium",      atomicMass: 238.029, category: .actinide,       group: nil,  period: 7, electronegativity: 1.38, meltingPointK: 1405.3,  boilingPointK: 4404.0,  discoveredYear: 1789, electronConfig: "[Rn] 5f³ 6d¹ 7s²",           funFact: "Uranium was used as an orange pigment in ceramics and glass ('uranium glass') from 1830 until WWII — it glows green under UV light.", uses: "Nuclear fuel, depleted uranium ammunition, radiation shielding"),
        Element(id: 93,  symbol: "Np", name: "Neptunium",    atomicMass: 237.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.36, meltingPointK: 912.0,   boilingPointK: 4175.0,  discoveredYear: 1940, electronConfig: "[Rn] 5f⁴ 6d¹ 7s²",           funFact: "Neptunium was the first transuranium element to be synthesized — it's named after Neptune, the planet beyond Uranus.", uses: "Neutron detection, production of Pu-238 for space probes"),
        Element(id: 94,  symbol: "Pu", name: "Plutonium",    atomicMass: 244.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.28, meltingPointK: 912.5,   boilingPointK: 3505.0,  discoveredYear: 1940, electronConfig: "[Rn] 5f⁶ 7s²",               funFact: "Plutonium-238 heat from radioactive decay powers the Voyager spacecraft, now in interstellar space 23 billion km from Earth.", uses: "Nuclear weapons, spacecraft RTGs, experimental reactors"),
        Element(id: 95,  symbol: "Am", name: "Americium",    atomicMass: 243.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.30, meltingPointK: 1449.0,  boilingPointK: 2880.0,  discoveredYear: 1944, electronConfig: "[Rn] 5f⁷ 7s²",               funFact: "Americium is in nearly every smoke detector — Am-241 ionizes air in the detector chamber, triggering an alarm when smoke interrupts the current.", uses: "Smoke detectors, neutron sources, cancer treatment research"),
        Element(id: 96,  symbol: "Cm", name: "Curium",       atomicMass: 247.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.30, meltingPointK: 1613.0,  boilingPointK: 3383.0,  discoveredYear: 1944, electronConfig: "[Rn] 5f⁷ 6d¹ 7s²",           funFact: "Curium glows red in the dark from intense radioactive decay — it generates more heat per gram than plutonium.", uses: "Alpha-particle X-ray spectrometers on Mars rovers, research"),
        Element(id: 97,  symbol: "Bk", name: "Berkelium",    atomicMass: 247.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.30, meltingPointK: 1259.0,  boilingPointK: nil,     discoveredYear: 1949, electronConfig: "[Rn] 5f⁹ 7s²",               funFact: "Berkelium, named after Berkeley, California, is produced in milligram quantities and costs about $185 million per gram.", uses: "Research, production of heavier elements like californium"),
        Element(id: 98,  symbol: "Cf", name: "Californium",  atomicMass: 251.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.30, meltingPointK: 1173.0,  boilingPointK: nil,     discoveredYear: 1950, electronConfig: "[Rn] 5f¹⁰ 7s²",              funFact: "Californium-252 is one of the most expensive materials on Earth — 1 microgram costs $60. It's used to start up nuclear reactors.", uses: "Neutron source for nuclear reactors, cancer treatment, oil well logging"),
        Element(id: 99,  symbol: "Es", name: "Einsteinium",  atomicMass: 252.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.30, meltingPointK: 1133.0,  boilingPointK: nil,     discoveredYear: 1952, electronConfig: "[Rn] 5f¹¹ 7s²",              funFact: "Einsteinium was discovered in the debris of the first hydrogen bomb test in 1952 and kept secret for years.", uses: "Research, production of heavier elements"),
        Element(id: 100, symbol: "Fm", name: "Fermium",      atomicMass: 257.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.30, meltingPointK: 1800.0,  boilingPointK: nil,     discoveredYear: 1952, electronConfig: "[Rn] 5f¹² 7s²",              funFact: "Fermium, named after Enrico Fermi, was also discovered in the Ivy Mike hydrogen bomb test fallout.", uses: "Research only — no practical applications"),
        Element(id: 101, symbol: "Md", name: "Mendelevium",  atomicMass: 258.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.30, meltingPointK: 1100.0,  boilingPointK: nil,     discoveredYear: 1955, electronConfig: "[Rn] 5f¹³ 7s²",              funFact: "Mendelevium was the first element produced one atom at a time — only 17 atoms were created in the original experiment.", uses: "Research only"),
        Element(id: 102, symbol: "No", name: "Nobelium",     atomicMass: 259.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.30, meltingPointK: 1100.0,  boilingPointK: nil,     discoveredYear: 1966, electronConfig: "[Rn] 5f¹⁴ 7s²",              funFact: "Nobelium's discovery was disputed for years between Soviet and American scientists during the Cold War.", uses: "Research only"),
        Element(id: 103, symbol: "Lr", name: "Lawrencium",   atomicMass: 266.000, category: .actinide,       group: nil,  period: 7, electronegativity: 1.30, meltingPointK: 1900.0,  boilingPointK: nil,     discoveredYear: 1961, electronConfig: "[Rn] 5f¹⁴ 7s² 7p¹",          funFact: "Lawrencium is named after Ernest Lawrence, inventor of the cyclotron particle accelerator used to create many synthetic elements.", uses: "Research only"),

        // Period 7 d-block (superheavy elements)
        Element(id: 104, symbol: "Rf", name: "Rutherfordium", atomicMass: 267.000, category: .transitionMetal, group: 4,  period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 1964, electronConfig: "[Rn] 5f¹⁴ 6d² 7s²",          funFact: "Rutherfordium was the first element discovered after the actinides — its creation was disputed between the USSR and USA.", uses: "Research only"),
        Element(id: 105, symbol: "Db", name: "Dubnium",      atomicMass: 268.000, category: .transitionMetal, group: 5,   period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 1968, electronConfig: "[Rn] 5f¹⁴ 6d³ 7s²",          funFact: "Dubnium is named after Dubna, Russia — named by IUPAC to settle the naming dispute between Russian and American research teams.", uses: "Research only"),
        Element(id: 106, symbol: "Sg", name: "Seaborgium",   atomicMass: 269.000, category: .transitionMetal, group: 6,   period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 1974, electronConfig: "[Rn] 5f¹⁴ 6d⁴ 7s²",          funFact: "Glenn Seaborg is the only person for whom an element was named while still alive — he lived to see it confirmed in 1994.", uses: "Research only"),
        Element(id: 107, symbol: "Bh", name: "Bohrium",      atomicMass: 270.000, category: .transitionMetal, group: 7,   period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 1981, electronConfig: "[Rn] 5f¹⁴ 6d⁵ 7s²",          funFact: "Bohrium is named after Niels Bohr, the Danish physicist who developed the Bohr model of the atom.", uses: "Research only"),
        Element(id: 108, symbol: "Hs", name: "Hassium",      atomicMass: 269.000, category: .transitionMetal, group: 8,   period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 1984, electronConfig: "[Rn] 5f¹⁴ 6d⁶ 7s²",          funFact: "Hassium was named after Hesse, the German state where the heavy ion research facility GSI is located.", uses: "Research only"),
        Element(id: 109, symbol: "Mt", name: "Meitnerium",   atomicMass: 278.000, category: .transitionMetal, group: 9,   period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 1982, electronConfig: "[Rn] 5f¹⁴ 6d⁷ 7s²",          funFact: "Meitnerium honors Lise Meitner, who co-discovered nuclear fission but was excluded from the Nobel Prize given to her male collaborator.", uses: "Research only"),
        Element(id: 110, symbol: "Ds", name: "Darmstadtium", atomicMass: 281.000, category: .transitionMetal, group: 10,  period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 1994, electronConfig: "[Rn] 5f¹⁴ 6d⁸ 7s²",          funFact: "Darmstadtium was created by bombarding nickel atoms into lead targets — only a few atoms have ever been observed.", uses: "Research only"),
        Element(id: 111, symbol: "Rg", name: "Roentgenium",  atomicMass: 282.000, category: .transitionMetal, group: 11,  period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 1994, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s¹",         funFact: "Roentgenium is named after Wilhelm Röntgen, discoverer of X-rays — appropriately, X-rays are used to study the shells of heavy atoms.", uses: "Research only"),
        Element(id: 112, symbol: "Cn", name: "Copernicium",  atomicMass: 285.000, category: .transitionMetal, group: 12,  period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 1996, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",         funFact: "Copernicium may be a gas at room temperature — relativistic effects on its outer electrons may prevent metallic bonding.", uses: "Research only"),
        Element(id: 113, symbol: "Nh", name: "Nihonium",     atomicMass: 286.000, category: .postTransition, group: 13,   period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 2004, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",    funFact: "Nihonium is named after Japan (Nihon in Japanese) — it was the first element discovered in Asia.", uses: "Research only"),
        Element(id: 114, symbol: "Fl", name: "Flerovium",    atomicMass: 289.000, category: .postTransition, group: 14,   period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 1999, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",    funFact: "Flerovium may be a gas at room temperature due to relativistic effects, despite being below lead in the periodic table.", uses: "Research only"),
        Element(id: 115, symbol: "Mc", name: "Moscovium",    atomicMass: 290.000, category: .postTransition, group: 15,   period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 2003, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",    funFact: "Moscovium was named after Moscow Oblast in Russia, where the Joint Institute for Nuclear Research is located.", uses: "Research only"),
        Element(id: 116, symbol: "Lv", name: "Livermorium",  atomicMass: 293.000, category: .postTransition, group: 16,   period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 2000, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",    funFact: "Livermorium is named after Lawrence Livermore National Laboratory — the element exists for only milliseconds.", uses: "Research only"),
        Element(id: 117, symbol: "Ts", name: "Tennessine",   atomicMass: 294.000, category: .halogen,        group: 17,   period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 2010, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",    funFact: "Tennessine is named after Tennessee, home to Oak Ridge National Laboratory, Vanderbilt University, and the University of Tennessee.", uses: "Research only"),
        Element(id: 118, symbol: "Og", name: "Oganesson",    atomicMass: 294.000, category: .nobleGas,       group: 18,   period: 7, electronegativity: nil,  meltingPointK: nil,     boilingPointK: nil,     discoveredYear: 2002, electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",    funFact: "Oganesson is the heaviest element and the only element named after a living person — physicist Yuri Oganessian, master of superheavy element synthesis.", uses: "Research only"),
    ]
    // swiftlint:enable function_body_length

    static func element(withNumber number: Int) -> Element? {
        all.first { $0.id == number }
    }

    static func elements(inCategory category: ElementCategory) -> [Element] {
        all.filter { $0.category == category }
    }
}
