import SwiftUI

/// A clean, light-mode report laid out for PDF rendering (612pt wide = US Letter). Designed to be
/// printed and handed to a pediatrician.
struct GrowthReportView: View {
    let child: Child
    let mass: MassUnit
    let length: LengthUnit
    let standard: GrowthStandardChoice

    private var summary: ChildSummary { ChildSummary.build(for: child) }

    var body: some View {
        VStack(alignment: .leading, spacing: 18) {
            header

            // Latest percentiles
            VStack(alignment: .leading, spacing: 8) {
                Text("Latest percentiles (\(standard.short) reference)")
                    .font(.system(size: 15, weight: .semibold, design: .rounded))
                HStack(spacing: 20) {
                    reportPercentile(.weight, summary.weightPercentile)
                    reportPercentile(.height, summary.heightPercentile)
                    reportPercentile(.head, summary.headPercentile)
                }
            }

            // Charts
            ForEach(GrowthMeasure.allCases) { measure in
                VStack(alignment: .leading, spacing: 6) {
                    Text(measure.title)
                        .font(.system(size: 14, weight: .semibold, design: .rounded))
                    GrowthChart(child: child, measure: measure, mass: mass, length: length, showAllOverlays: true)
                        .frame(height: 180)
                }
            }

            // History table
            VStack(alignment: .leading, spacing: 6) {
                Text("Measurement history")
                    .font(.system(size: 15, weight: .semibold, design: .rounded))
                historyTable
            }

            Spacer(minLength: 0)
            Text("Generated by Sprig on \(Date().formatted(date: .abbreviated, time: .omitted)). Informational only — not medical advice.")
                .font(.system(size: 10, design: .rounded))
                .foregroundStyle(.secondary)
        }
        .padding(28)
        .frame(width: 612, alignment: .leading)
        .background(Color.white)
        .foregroundStyle(Color.black)
    }

    private var header: some View {
        HStack(alignment: .top) {
            VStack(alignment: .leading, spacing: 4) {
                Text("Growth Report")
                    .font(.system(size: 24, weight: .bold, design: .rounded))
                Text(child.displayName)
                    .font(.system(size: 18, weight: .semibold, design: .rounded))
                Text("\(child.sex.title) · \(summary.ageDescription) · born \(child.birthDate.formatted(date: .abbreviated, time: .omitted))")
                    .font(.system(size: 12, design: .rounded))
                    .foregroundStyle(.secondary)
            }
            Spacer()
            Image(systemName: "leaf.fill")
                .font(.system(size: 30))
                .foregroundStyle(Color(hex: 0x3F9D6B))
        }
    }

    private func reportPercentile(_ measure: GrowthMeasure, _ result: PercentileResult?) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(measure.shortTitle)
                .font(.system(size: 11, weight: .semibold, design: .rounded))
                .foregroundStyle(.secondary)
            Text(result.map { PercentileEngine.ordinal($0.percentile) } ?? "—")
                .font(.system(size: 20, weight: .bold, design: .rounded))
        }
    }

    private var historyTable: some View {
        VStack(alignment: .leading, spacing: 0) {
            tableRow(date: "Date", age: "Age",
                     weight: "Weight", height: "Height", head: "Head", header: true)
            ForEach(child.sortedMeasurements) { m in
                tableRow(date: m.date.formatted(date: .abbreviated, time: .omitted),
                         age: AgeMath.description(from: child.birthDate, to: m.date),
                         weight: m.weightKg.map { UnitConvert.format($0, measure: .weight, mass: mass, length: length) } ?? "—",
                         height: m.heightCm.map { UnitConvert.format($0, measure: .height, mass: mass, length: length) } ?? "—",
                         head: m.headCm.map { UnitConvert.format($0, measure: .head, mass: mass, length: length) } ?? "—",
                         header: false)
            }
        }
    }

    private func tableRow(date: String, age: String, weight: String, height: String, head: String, header: Bool) -> some View {
        HStack(spacing: 0) {
            cell(date, width: 110, header: header)
            cell(age, width: 90, header: header)
            cell(weight, width: 110, header: header)
            cell(height, width: 110, header: header)
            cell(head, width: 110, header: header)
        }
        .background(header ? Color(hex: 0xEFEDE4) : Color.white)
    }

    private func cell(_ text: String, width: CGFloat, header: Bool) -> some View {
        Text(text)
            .font(.system(size: 11, weight: header ? .semibold : .regular, design: .rounded))
            .frame(width: width, alignment: .leading)
            .padding(.vertical, 4)
            .padding(.horizontal, 4)
    }
}
