import SwiftUI

/// A clean, self-contained summary card for clinicians. Uses literal colors (no environment)
/// so it renders identically when exported via `ImageRenderer`.
struct DoctorReportCard: View {
    let summary: InsightsEngine.Summary

    private var rangeText: String {
        guard let start = summary.rangeStart, let end = summary.rangeEnd else { return "No dated logs" }
        let s = start.formatted(date: .abbreviated, time: .omitted)
        let e = end.formatted(date: .abbreviated, time: .omitted)
        return "\(s) – \(e)"
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            HStack {
                Image(systemName: "leaf.fill")
                Text("Equinox — Symptom Summary")
                    .font(.system(size: 16, weight: .bold, design: .rounded))
                Spacer()
            }
            .foregroundStyle(Color(hex: 0x2A1F18))

            Divider().overlay(Color(hex: 0xD88A55).opacity(0.4))

            row("Date range", rangeText)
            row("Days logged", "\(summary.daysLogged)")
            row("Avg hot flashes / day", String(format: "%.1f", summary.avgHotFlashesPerDay))
            row("Total hot flashes", "\(summary.totalHotFlashes)")
            row("Nights with sweats", "\(summary.nightSweatDays)")
            if let mood = summary.avgMood { row("Avg mood (1–5)", String(format: "%.1f", mood)) }
            if let sleep = summary.avgSleep { row("Avg sleep (1–5)", String(format: "%.1f", sleep)) }

            VStack(alignment: .leading, spacing: 6) {
                Text("TOP SYMPTOMS")
                    .font(.system(size: 11, weight: .bold, design: .rounded))
                    .foregroundStyle(Color(hex: 0x988372))
                if summary.topSymptoms.isEmpty {
                    Text("None recorded")
                        .font(.system(size: 13, design: .rounded))
                        .foregroundStyle(Color(hex: 0x6A5849))
                } else {
                    ForEach(summary.topSymptoms) { s in
                        HStack {
                            Text(s.name)
                                .font(.system(size: 13, weight: .medium, design: .rounded))
                                .foregroundStyle(Color(hex: 0x2A1F18))
                            Spacer()
                            Text("\(s.daysPresent) days · avg \(String(format: "%.1f", s.avgSeverity))")
                                .font(.system(size: 12, design: .rounded))
                                .foregroundStyle(Color(hex: 0x6A5849))
                        }
                    }
                }
            }

            VStack(alignment: .leading, spacing: 4) {
                Text("CYCLE")
                    .font(.system(size: 11, weight: .bold, design: .rounded))
                    .foregroundStyle(Color(hex: 0x988372))
                Text(cycleLine)
                    .font(.system(size: 13, design: .rounded))
                    .foregroundStyle(Color(hex: 0x2A1F18))
                    .fixedSize(horizontal: false, vertical: true)
            }

            Text("Informational only — not a diagnosis. Generated by Equinox on this device.")
                .font(.system(size: 10, design: .rounded))
                .foregroundStyle(Color(hex: 0x988372))
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(22)
        .frame(width: 360)
        .background(Color(hex: 0xFFFBF6))
        .overlay(
            RoundedRectangle(cornerRadius: 18, style: .continuous)
                .strokeBorder(Color(hex: 0xEADCCC), lineWidth: 1)
        )
        .clipShape(RoundedRectangle(cornerRadius: 18, style: .continuous))
    }

    private var cycleLine: String {
        let c = summary.cycle
        var parts: [String] = []
        if let d = c.daysSinceLastPeriod { parts.append("\(d) days since last period") }
        if let g = c.longestGap { parts.append("longest recent gap \(g) days") }
        parts.append(c.stage.rawValue)
        return parts.isEmpty ? "No cycle data" : parts.joined(separator: " · ")
    }

    private func row(_ label: String, _ value: String) -> some View {
        HStack {
            Text(label)
                .font(.system(size: 13, design: .rounded))
                .foregroundStyle(Color(hex: 0x6A5849))
            Spacer()
            Text(value)
                .font(.system(size: 14, weight: .semibold, design: .rounded))
                .foregroundStyle(Color(hex: 0x2A1F18))
        }
    }
}

/// Plain-text version of the report for the share sheet (alongside the rendered image).
enum DoctorReportText {
    static func make(from summary: InsightsEngine.Summary) -> String {
        var lines: [String] = ["Equinox — Symptom Summary"]
        if let start = summary.rangeStart, let end = summary.rangeEnd {
            lines.append("Range: \(start.formatted(date: .abbreviated, time: .omitted)) – \(end.formatted(date: .abbreviated, time: .omitted))")
        }
        lines.append("Days logged: \(summary.daysLogged)")
        lines.append("Avg hot flashes/day: \(String(format: "%.1f", summary.avgHotFlashesPerDay)) (total \(summary.totalHotFlashes))")
        lines.append("Nights with sweats: \(summary.nightSweatDays)")
        if let mood = summary.avgMood { lines.append("Avg mood: \(String(format: "%.1f", mood))/5") }
        if let sleep = summary.avgSleep { lines.append("Avg sleep: \(String(format: "%.1f", sleep))/5") }
        if !summary.topSymptoms.isEmpty {
            lines.append("Top symptoms:")
            for s in summary.topSymptoms {
                lines.append("  • \(s.name): \(s.daysPresent) days, avg severity \(String(format: "%.1f", s.avgSeverity))")
            }
        }
        let c = summary.cycle
        if let d = c.daysSinceLastPeriod { lines.append("Days since last period: \(d)") }
        if let g = c.longestGap { lines.append("Longest recent cycle gap: \(g) days") }
        lines.append("Stage note: \(c.stage.rawValue)")
        lines.append("")
        lines.append("Informational only — not a diagnosis. Generated by Equinox on-device.")
        return lines.joined(separator: "\n")
    }
}
