import SwiftUI

/// About screen: what Verbo is and how it works.
struct AboutView: View {
    var body: some View {
        ZStack {
            Theme.bg.ignoresSafeArea()
            ScrollView {
                VStack(spacing: 18) {
                    VStack(spacing: 10) {
                        Image(systemName: "text.book.closed.fill")
                            .font(.system(size: 48))
                            .foregroundStyle(Theme.accent)
                            .accessibilityHidden(true)
                        Text("Verbo")
                            .font(Theme.serif(30, .bold))
                            .foregroundStyle(Theme.ink)
                        Text("Spanish & French verb conjugation trainer")
                            .font(Theme.rounded(15))
                            .foregroundStyle(Theme.inkSoft)
                            .multilineTextAlignment(.center)
                    }
                    .padding(.top, 16)

                    infoCard(title: "A real conjugation engine",
                             body: "Every answer Verbo quizzes you on is generated by a built-in conjugation engine — regular endings computed live, common irregulars from a curated lookup table. No hardcoded answer keys to run out of.")
                    infoCard(title: "Adaptive practice",
                             body: "Verbo tracks mastery for each verb and tense and weights your drills toward weak spots, so your time goes where it helps most.")
                    infoCard(title: "Yours, offline",
                             body: "Everything runs on-device with no account and no network. Pro is a one-time unlock, not a subscription.")

                    Text("Version 1.0")
                        .font(Theme.rounded(13))
                        .foregroundStyle(Theme.inkFaint)
                        .padding(.top, 6)
                }
                .padding(20)
            }
        }
        .navigationTitle("About")
        .navigationBarTitleDisplayMode(.inline)
    }

    private func infoCard(title: String, body: String) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(title)
                .font(Theme.serif(17, .semibold))
                .foregroundStyle(Theme.ink)
            Text(body)
                .font(Theme.rounded(15))
                .foregroundStyle(Theme.inkSoft)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(18)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(RoundedRectangle(cornerRadius: 16, style: .continuous).fill(Theme.surface))
    }
}
